### PR TITLE
fix: loader js does not see other preview types

### PR DESCRIPTION
**Pull request by zakharchenkoAndrii**
Issue: https://github.com/storybookjs/react-native/issues/295

## What I did
changed loader a bit

## How to test

Create files with different extensions. The generated file should not fail to populate with decorators and parameters

### CODE REVIEW

**Comment by dannyhw** [comment]
Hey thats awesome! Thanks for your contribution. 

Could you add test cases also? 🙏

The tests are in loader.tests.js in the same folder.

**Comment by zakharchenkoAndrii** [comment]
> Hey thats awesome! Thanks for your contribution.
> 
> Could you add test cases also? 🙏
> 
> The tests are in loader.tests.js in the same folder.

done 😉

**Comment by zakharchenkoAndrii** [comment]
> Hey thats awesome! Thanks for your contribution.
> 
> Could you add test cases also? 🙏
> 
> The tests are in loader.tests.js in the same folder.

done 😉

**Comment by dannyhw** [comment]
I don't have much time now but soon I'll check it.

**Comment by dannyhw** [comment]
@zakharchenkoAndrii nice change, thanks! 🙇

**Pull request merged**
