### PR TITLE
Add core config

### PR DESCRIPTION
**Pull request by trajano**
This is needed to disable telemetry

Issue:

## How to test

Please explain how to test your changes and consider the following questions

- Does this need a new example in examples/expo-example?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by dannyhw** [comment]
I think there might be some extra steps needed to make the config actually apply since this config for rn storybook is parsed manually by the generate script. Have you confirmed that telemetry is going out? And is it being turned off by this option?

**Comment by trajano** [comment]
Nope, I just saw Telemetry config in the documentation while I was doing the update and I was just expecting the typings for the config to be relatively the same.  I am primarily putting it to disable the telemetry in case it is doing telemetry.

**Comment by dannyhw** [comment]
I will check this but it was my understanding that telemetry is not going out since its not explicitly implemented for rn storybook

**Comment by trajano** [comment]
Awesome, it would be nice to know in the documentation that it is not supported by RN storybook in case people have privacy concerns.

**Comment by dannyhw** [comment]
I'm fairly confident that no telemetry is going out from react native and this config would have no impact. If I find anything that contradicts that I will revisit this. Thanks for bringing it up though!

**Pull request closed without merging**
