### PR TITLE
Fix safe area stories cut off

### PR DESCRIPTION
**Pull request by jonathanj**
Issue:

In stories with `noSafeArea: false` (the default), the available space for story content is cut off at the bottom (going below the navigation bar) even when hiding the navigation UI.

## What I did

I removed the `marginTop` adjustment in the preview area, this seems to not be necessary for `noSafeArea: false` or `noSafeArea: true` stories, the translate-Y adjustment is perfectly fine.

## How to test

I added a new "Usable area" story that has an absolute-filled box, all 4 borders of the box should always be visible and `noSafeArea` should dictate how much of the screen is allowed to be occupied by the story content.

| Before | After |
|--------|------|
| image            |  image |

### CODE REVIEW

**Comment by jonathanj** [comment]
A colleague showed me this issue: https://github.com/storybookjs/react-native/issues/265

Do you think it is related? I’d be happy to test the changes in this PR against that issue, but I’m not sure I know how to reproduce it. Does it require a specific Android simulator on a specific Android version? Does it need to also be an Expo project?

**Comment by dannyhw** [comment]
@jonathanj yeah exactly it only happened on certain emulators on expo, pixel 4a it looks like. However it was fixable on the user side i think by adding a safearea. Though it might be a statusbar height thing, not sure.

The issue you're referring to is really old though.

**Comment by dannyhw** [comment]
I need to check this but I think margin top has to do with a weird jump in the animation that would happen

**Comment by jonathanj** [comment]
> I need to check this but I think margin top has to do with a weird jump in the animation that would happen

Happy to have any input for things I might have missed, but I personally didn't notice any animation jump on Android or iOS.

**Comment by jonathanj** [comment]
> @jonathanj yeah exactly it only happened on certain emulators on expo, pixel 4a it looks like. However it was fixable on the user side i think by adding a safearea. Though it might be a statusbar height thing, not sure.
> 
> The issue you're referring to is really old though.

I couldn't seem to reproduce anything like this, since there have been a number of changes to the safe area since that issue, do you think it's still relevant?

**Comment by dannyhw** [comment]
I'll try it out when I can and double check but it looks good so I'm assuming there won't be any issue.

**Comment by jonathanj** [comment]
> I need to check this but I think margin top has to do with a weird jump in the animation that would happen

@dannyhw I looked into this more carefully and you're right, there is a weird jump/wobble that happens in the animation removing the `marginTop`. I ended up reworking the way the animation/safe area stuff works, and improving the scaled preview view and the animations around it. I think this solves all of the issues I saw reported and about the safe area and the one I was having specifically with elements being cut off.

I also think the changes to the scaled preview make it much clearer with regards to what space the story content occupies on the device screen. See attached video.

Repeated from the commit message:

In order to create more a more stable animation, one that isn't
affected by safe areas popping in/out, a few refactorings were
necessary:

- Remove the use of `SafeAreaView` and instead manually manage the
  margin using the values from `useSafeAreaInsets`
- Use a stable Y-translation for the scaled preview, to ensure it is
  at the same position regardless of safe area presence, or UI
  visibility

Some additional improvements:

- Center the scaled preview horizontally in the available space,
  instead of using a fixed pixel offset (TRANSLATE_X_OFFSET)
- Reduce the number of views and animated views necessary to achieve
  the animation
- Add a shadow to the scaled preview to indicate the device screen
  area in relation to the story content area
- Measure the navigation bar height, instead of using a fixed value
  that is differently incorrect on each platform
- Add comments to code where explaining something not obvious could
  help the next developer


https://user-images.githubusercontent.com/112166/221198072-1c4b94a3-fd43-457c-a67b-136448fe3a90.mp4

**Comment by dannyhw** [comment]
@jonathanj I'm not sure if this is directly because of these changes but the web UI (wide screen) got a horizontal scroll. 

The web support isn't a focus but its nice to have the widescreen version working so you can use an Ipad simulator for example.

actually I checked and on the ipad it seems fine.

**Review by dannyhw — APPROVED** [review]
Thanks for your contribution 🙇 . This is really great 💯 .

**Pull request merged**
