### PR TITLE
fix: v5 notes addon crash and fail to install

### PR DESCRIPTION
**Pull request by dannyhw**
Issue: #46 

There were lots of issues when I tried to make a build with the notes addon bug and I attempted to resolve some of them here. 

Will make a release soon.

### CODE REVIEW

**Comment by AlexanderEggers** [comment]
@dannyhw When do you plan to merge this PR? I was thinking of contribute some work to the project but there is probably not much a point unless this one is merged and somewhat stable.

**Comment by dannyhw** [comment]
@AlexanderEggers 

I've been away recently so haven't had time, sorry for the wait.

the fix is ready but i had trouble on the master branch getting the ci to pass. Generally I've been putting fixes on the next (beta) branch so I haven't done any builds on master for a while. If its an option I'd say disable the notes addon for now if you need to get past the error. 

I will try to do a pre-release with the fix tomorrow if I can and once I confirm it's working I'll make a new stable version.

**Comment by dannyhw** [comment]
Seems like linting is just failing because a package needs to be added, these changes are from the react native upgrade.

**Comment by dannyhw** [comment]
now testable on 

 - @storybook/addon-ondevice-knobs@5.3.26-alpha.0
 - @storybook/addon-ondevice-notes@5.3.26-alpha.0

**Comment by dannyhw** [comment]
linting is failing but its not a big deal since the linting was reworked for the next-6.0 branch

**Pull request merged**
