### PR TITLE
feat: add web to the example

### LINKED ISSUE #170: [6.0] add react native web to the example app
As part of the work by @oblador to remove no-hoisting we removed some of the example projects to slim down the project. This meant removing the expo example which had a web example.

We should add react-native-web to the example app and get something basic rendering.

There may be some changes needed in the project to make this work. Making this work with ondevice knobs will require #120 to be fixed so that should be considered out of the scope of this issue

### PR DESCRIPTION
**Pull request by dannyhw**
Issue: closes #170 

## What I did

I added react native web to the example project.

I've followed this blog post https://arry.medium.com/how-to-add-react-native-web-to-an-existing-react-native-project-eb98c952c12f

Some config was adjusted, however for the most part it remains the same as in the blog.

## How to test

1. `cd examples/native`
2. `yarn web`

### CODE REVIEW

**Review by barnsdev — APPROVED** [review]
Checked out and ran `yarn web` and all working fine in browser.

Checked that iOS and Android still working fine too and all good there.

Looks good to me @dannyhw

**Comment by sangameshsomawar** [comment]
@devBarn : Getting errors while running `yarn web` on both branches (feat/example-react-native-web and next-6.0)
Please help.

Screenshot 2021-11-15 at 10 23 59 AM

**Comment by dannyhw** [comment]
@sangameshsomawar try running `yarn prepareAll` in the root of the project.

**Comment by sangameshsomawar** [comment]
@dannyhw : Now it's working, Please explain the magic of yarn prepareAll.

One more question, how to build this as a static website,
I tried with the below approach, It created a dist folder but I could not open it as a static site.
    "build-react": "webpack --mode production --config webpack.config.js"

**Comment by sangameshsomawar** [comment]
@dannyhw 

`http-server dist/` this is working for me. Do you have any other way to serve as a static site?

**Comment by dannyhw** [comment]
@sangameshsomawar prepare all just runs prepare on every package. It's possible that something didn't work during the bootstrap command for you.

Could you create an issue about the build command because I think this PR is not the right place for that.

I haven't really tried to make a build since that's more like a webpack config thing as far as I can tell and not necessarily needed for our example app.

**Comment by sangameshsomawar** [comment]
@dannyhw Thanks,
 I will create new issue for build command.

**Pull request merged**
