### PR TITLE
feat: allow for main.ts or any other file extension

### PR DESCRIPTION
**Pull request by dannyhw**
Issue: #390

## What I did

Added logic to allow any file extension for main.

## How to test

run the stories loader script for a project with main.ts

### CODE REVIEW

**Comment by diginikkari** [comment]
I think this should also be tested using very common `default export' format. Not only extension change.:

``` typescript
import type { StorybookConfig } from '@storybook/core-common';

const config: StorybookConfig = {
  stories: ['./FakeStory.stories.tsx'],
  addons: [
    '@storybook/addon-ondevice-notes',
    '@storybook/addon-ondevice-controls',
    '@storybook/addon-ondevice-backgrounds',
    '@storybook/addon-ondevice-actions',
  ],
};

export default config;
```

**Comment by dannyhw** [comment]
@diginikkari test case added and a fix for default exports.

**Comment by diginikkari** [comment]
@dannyhw looks good 👍 Now with the watcher changes this should help working with typescript 😀.
I'm so happy how RN Storybook is getting closer to current storybook. When having used to develop components in isolation with web it's so nice to be able to do it also with RN.

**Comment by dannyhw** [comment]
@diginikkari thats really great to hear, thanks :).

We have some cool plans for react native in future too 😄

**Comment by diginikkari** [comment]
> We have some cool plans for react native in future too 😄

oh, looking forward to those 👀

**Pull request merged**
