### PR TITLE
fix: add missing devDependency(ts-dedent)

### PR DESCRIPTION
**Pull request by duguyihou**
Issue:

## What I did

add `ts-dedent` to devDependency

## How to test

`ts-dedent` is not in the devDependency list but it is required in `StoryHash.ts`

storybookdemo

Please explain how to test your changes and consider the following questions

- Does this need a new example in examples/expo-example? No
- Does this need an update to the documentation? No

### CODE REVIEW

**Comment by dannyhw** [comment]
weird that I never saw this before but I guess it should just be a regular dependency not dev dependency right?

**Comment by duguyihou** [comment]
In storybookJS project, it is in devDependency as well. image

**Comment by dannyhw** [comment]
hmm well its probably just prebundling it thats why, anyway I think this is fine to merge

**Comment by dannyhw** [comment]
Thanks for the contribution 👍

**Pull request merged**
