### PR TITLE
feat: add number feedback to range slider, minor change onSlidingComplete

### PR DESCRIPTION
**Pull request by CezarCobuz**
Issue: [discussion-334](https://github.com/storybookjs/react-native/discussions/334) 

## What I did

Added text value for number range based on this [discussion](https://github.com/storybookjs/react-native/discussions/334)  
Non-related to discussion: changed onSlidingComplete to onValueChange for faster feedback. 

## How to test

Can be testing using existing Number control > Range 

https://user-images.githubusercontent.com/36707637/156063674-3c9e62de-d295-467b-8e36-1b14573a6ccb.mov

### CODE REVIEW

**Comment by dannyhw** [comment]
Thanks for your contribution 🙏🙇‍♂️.

Looks good! Only thing is I'd like to see how it looks on Android too. I can give it a quick test tomorrow probably.

**Comment by CezarCobuz** [comment]
> Thanks for your contribution 🙏🙇‍♂️.
> 
> Looks good! Only thing is I'd like to see how it looks on Android too. I can give it a quick test tomorrow probably.

Here is a preview on android: 
https://user-images.githubusercontent.com/36707637/156105293-0ff1b30a-45ac-4503-b6ff-1467003478b9.mov

**Comment by dannyhw** [comment]
thanks @CezarCobuz sorry for the delay, having a look now!

**Comment by dannyhw** [comment]
There is some strange behaviour with the slider on android, I don't think its caused by your changes though.

**Comment by dannyhw** [comment]
Made a small adjustment, hope you don't mind!

image

Great contribution, thanks again 🙇

**Comment by dannyhw** [comment]
now live in 6.0.1-beta.5

**Pull request merged**
