### PR TITLE
refactor: Refactor OndeviceUI components to function components

### PR DESCRIPTION
**Pull request by lauriharpf**
Issue: https://github.com/storybookjs/react-native/issues/179

## What I did
Refactored components under app/react-native/src to function components, with the exception of Addons.tsx (done in https://github.com/storybookjs/react-native/pull/187).

This also updates `Podfile.lock` in the `examples/native` as a result of running `pod install` for iOS.

## How to test

Run the native examples and check that the Storybook UI works correctly.

- Does this need a new example in examples/native? **In my opinion, no**
- Does this need an update to the documentation? **In my opinion, no**

### CODE REVIEW

**Comment by dannyhw** [comment]
@lauriharpf sorry I haven't got around to reviewing your changes on #187 yet, not had the time . I'll be able to do it this coming week though for sure, including this one :).

Thanks again for your contribution.

**Comment by lauriharpf** [comment]
> @lauriharpf sorry I haven't got around to reviewing your changes on #187 yet, not had the time . I'll be able to do it this coming week though for sure, including this one :).
> 
> Thanks again for your contribution.

Thanks! No worries, there are many other things in life in addition to maintaining open source projects 🙂 . Your quick responses and welcoming attitude are much appreciated!

**Comment by lauriharpf** [comment]
Noticed that out of the components under `app/react-native` there was only one class component (StoryListView) remaining. Wasn't a big job to convert, so did it in 7d9495f which is now included in this PR.

Not currently planning to touch the addon components as it might conflict quite a bit with https://github.com/storybookjs/react-native/pull/182 . Please ping if there's something that I can do to help out 🙂 .

**Comment by dannyhw** [comment]
@lauriharpf I'm actually thinking of pushing the current changes in #182 so that it will be easier to collaborate on the addon changes. It will probably be a little bit unfinished/broken temporarily however #182 is getting too big to deal with currently so I think it would make sense to split the controls feature into parts. Does that seem reasonable to you? Depending on feedback I might merge that later tonight after a few changes.

**Comment by lauriharpf** [comment]
> @lauriharpf I'm actually thinking of pushing the current changes in #182 so that it will be easier to collaborate on the addon changes. It will probably be a little bit unfinished/broken temporarily however #182 is getting too big to deal with currently so I think it would make sense to split the controls feature into parts. Does that seem reasonable to you? Depending on feedback I might merge that later tonight after a few changes.

@dannyhw , that sounds like a good idea. Not sure about the state of #182, but if merging it wouldn't break any functionality then it sounds wise to merge :+1:. If merging would cause severe regressions or add a great deal of technical debt, then we could also try working on #182 together: If there are clearly separate tasks you'd like to get done, I could branch off #182 and then make a PR back to #182.

Would go with whatever helps you out the most & helps get the first 6.X-based release out the door fastest, even if it would be a pretty crude alpha release 🙂 .

**Review by dannyhw — APPROVED** [review]
Looks good to me!
I also ran it on my machine and it seemed fine.

Thanks for your contribution 🙇

**Pull request merged**
