### PR TITLE
Updated example project to 0.65

### PR DESCRIPTION
**Pull request by shikharvashistha**
Issue: #267 

## What I did

Greetings of the day,

I've updated example project to 0.65 using upgrade helper. Please review the pr and let me know in case of any changes if required.

Thanks & Regards
Shikhar Vashistha

### CODE REVIEW

**Comment by dannyhw** [comment]
@shikharvashistha thanks a lot for your contribution :). Will check it soon.

**Comment by dannyhw** [comment]
sorry its been a busy week for me, I haven't forgotten about this PR though

**Comment by shikharvashistha** [comment]
> sorry its been a busy week for me, I haven't forgotten about this PR though

no worries 😄

**Comment by dannyhw** [comment]
@shikharvashistha I'm getting an error when I run the example
```
 ERROR  Invariant Violation: View config getter callback for component `RCTText` must be a function (received `undefined`).
 ```

At first I thought it was an issue with emotion but after testing emotion on a fresh repo I wasn't able to reproduce the issue.

**Comment by dannyhw** [comment]
Looked into it there are some other react-native dependencies in the project that need to be updated also. I'll push some changes to your branch with the fix, hope you don't mind :).

**Pull request merged**
